plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  # Parcel
  '@parcel/transformer-image@2.0.1':
    peerDependencies:
      '@parcel/core': '^2.0.1'
  '@parcel/types@2.0.1':
    peerDependencies:
      '@parcel/core': '^2.0.1'
  '@parcel/packager-html@2.0.1':
    peerDependencies:
      '@parcel/core': '^2.0.1'
  '@parcel/packager-svg@2.0.1':
    peerDependencies:
      '@parcel/core': '^2.0.1'
  '@parcel/reporter-cli@2.0.1':
    peerDependencies:
      '@parcel/core': '^2.0.1'
  '@parcel/plugin@2.0.1':
    peerDependencies:
      '@parcel/core': '^2.0.1'
  '@parcel/bundler-default@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/compressor-raw@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/namer-default@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-cssnano@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-htmlnano@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-image@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-svgo@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-terser@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-css@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-js@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-raw@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-ts@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/reporter-dev-server@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/resolver-default@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-browser-hmr@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-js@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-react-refresh@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-service-worker@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-babel@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-css@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-html@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-js@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-json@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-postcss@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-posthtml@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-raw@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-react-refresh-wrap@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-svg@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-typescript-types@*':
    peerDependencies:
      '@parcel/core': '*'
  # Fluent UI
  '@fluentui/style-utilities@*':
    peerDependencies:
      'react': '*'
      '@types/react': '*'
  '@fluentui/font-icons-mdl2@*':
    peerDependencies:
      'react': '*'
      '@types/react': '*'
  'styled-components@*':
    dependencies:
      'react-is': '*'
  '@testing-library/user-event@*':
    dependencies:
      '@testing-library/dom': '*'
  'rollup-plugin-visualizer@*':
    dependencies:
      'rollup': '*'
